# Generated by Django 3.1.2 on 2020-10-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
