# Generated by Django 3.1.2 on 2020-10-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip',
        ),
    ]
